#!/usr/bin/python
import os
import subprocess
import urllib2
import json

home = os.path.expanduser('~')
f = open(home+'/.gitconfig')
lines = f.readlines()
f.close()

for line in lines:
  if "email" in line:
    email = "".join(line.split(" "))
    email = email[email.index("=")+1:]
    break

avatar = "http://www.gravatar.com/avatar/"+email
p = subprocess.Popen('git log -1 --oneline', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
for line in p.stdout.readlines():
  message = line,
  retval = p.wait()

if "#fcmln" in message:
  data = json.dumps({"email":email, "message":message})
  url = "http://akenn.org:9000"
  req = urllib2.Request(url, data, {'Content-Type': 'application/json'})
  f = urllib2.urlopen(req)
  response = f.read()
  f.close()
