#!/usr/bin/python
import os
import subprocess
import urllib2
import json

home = os.path.expanduser('~')
f = open(home+'/.gitconfig')
lines = f.readlines()
f.close()

for line in lines:
  if "email" in line:
    email = "".join(line.split(" "))
    email = email[email.index("=")+1:]
    break

f = open('.git/config')
lines = f.readlines()
f.close()
for line in lines:
  if "url" in line:
    remote = line.split("/")
    owner = remote[len(remote)-2]
    if ":" in owner:
      owner = owner.split(":")
      owner = owner[len(owner)-1]
    remote = str(owner) + "/" + remote[len(remote)-1][:-5]
    break

p = subprocess.Popen('git log -1 --oneline', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
for line in p.stdout.readlines():
  message = line,
  retval = p.wait()
message = message[0]

if "#cfln" in message:
  data = json.dumps({"email":email, "message":message, "remote": remote})
  url = "http://commits.feathrapp.com"
  req = urllib2.Request(url, data, {'Content-Type': 'application/json'})
  f = urllib2.urlopen(req)
  response = f.read()
  f.close()
